# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c2c8733bad931da4abcf4d926a340792b4fa92d01f46557887e95a6a59f75d023b93f4c3d798e48a0e9fe118083da85cfa818358724433badc0ba3bd5fccd010

test:
  secret_key_base: ee8ea2f0f4a79275bb50bea1e7599251a374e7a70c652433411165130afd135c4539dec6c8c50b5c495216a308727eff127d6d5390ec93cd230a04c7dbc70636

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
